apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
  namespace: bookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
        - name: book-api
          image: us-central1-docker.pkg.dev/example/book-api-dev/book-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: book-api-config
                  key: APP_ENV
            - name: DOCKER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: book-db-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
