apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-db
  namespace: bookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-db
  template:
    metadata:
      labels:
        app: book-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: dbadminpassword
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: bookstore
